server:
  port: 8086

spring:
  application:
    name: websocket-gateway
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092

livequiz:
  answer-service:
    url: http://localhost:8083

---
spring:
  config:
    activate:
      on-profile: docker
  data:
    redis:
      host: redis
  kafka:
    bootstrap-servers: kafka:29092

livequiz:
  answer-service:
    url: http://answer-processing:8083

